2017: adapt to final rules
roboterclubaachen/eurobot-resources pull request #2
Opened 2016-12-13 00:40 UTC by daniel-k

This should fix #1, but is not complete yet. Moving the titanium ores in the big craters is a mess doing by hand. However, using Inkscape to move elements messes up all the handcrafted file structure 🙁 

Second, I struggled rotating the rockets. I ended up with `transform=rotate(...) translate(...)` with weird coordinates.

Any suggestions?

Last but not least it looks like you have mirrored the colors creating the new playground. But maybe I'm missing something?

2016-12-13 01:19 UTC, salkinium commented
> Moving the titanium ores in the big craters is a mess doing by hand. However, using Inkscape to move elements messes up all the handcrafted file structure

I'm (ab)using SVG as a (visual) data store for further processing (see internal wiki Meetings/2016-02-02). The entire point of this was to create a way to easily visualize our robot data such as routes, regions and objects in the simulator by modifying the SVG DOM and then having it rendered live. The visualization aspect of this is the key, as it is standardized and thus could be displayed by a web browser (and served by the debug-server).
Furthermore, SVGs geometric primitives are exactly what we are using already and the coordinates can be specified exactly too. Unfortunately I left before I could get around to implementing a prototype.

But I disgress, yes, you cannot use an SVG editor, you must code it by hand. Suffer, you must. BWAHAHA.

> Last but not least it looks like you have mirrored the colors creating the new playground. But maybe I'm missing something?

[The Readme is actually quite good](https://github.com/roboterclubaachen/eurobot-resources#coordinate-system) 😢. Specifically:
> Please note that the y-axis grows "upwards", and not "downwards" as in most graphics coordinate systems.

Your webbrowser like most window system have the coordinate origins at the upper left corner, growing x right and y down. Hence, if you don't use `viewer.svg` you will see a mirrored image.

(This is just a polite way of telling you to RTFM).

> Second, I struggled rotating the rockets. I ended up with transform=rotate(...) translate(...) with weird coordinates.

The rockets are drawn left of the origin and then only translated up or down.
Since you are rotating around the origin of the SVG and 2D transformations are not commutative, you don't get the results you expect.
Now that you need to rotate them I recommend drawing the rockets at (0,0), then rotate, and translate them as needed.

2016-12-13 02:03 UTC, salkinium requested changes

2016-12-13 02:03 UTC, salkinium commented on 2017/playground.svg
> +			<rect x="-800" y="-70" width="600" height="28" zheight="28"/>
2mm less height requires compensation in y origin:
```diff
- <rect x="-800" y="-70" width="600" height="28" zheight="28"/>
+ <rect x="-800" y="-68" width="600" height="28" zheight="28"/>
```

2016-12-13 02:03 UTC, salkinium commented on 2017/playground.svg
>  	<!-- identifiers ordered -y => +y -->
For crater 2:
```xml
	<!-- crater 2 -->
	<use x="-455"  y="-905"  id="titanium-ore-21"  xlink:href="#titanium-ore"/>
	<use x="-512"  y="-867"  id="titanium-ore-22"  xlink:href="#titanium-ore"/>
	<use x="-405"  y="-865"  id="titanium-ore-23"  xlink:href="#titanium-ore"/>
	<use x="-495"  y="-805"  id="titanium-ore-24"  xlink:href="#titanium-ore"/>
	<use x="-430"  y="-800"  id="titanium-ore-25"  xlink:href="#titanium-ore"/>
```
For crater 5:
```xml
	<!-- crater 5 -->
	<use x="-430"  y="800"   id="titanium-ore-36"  xlink:href="#titanium-ore"/>
	<use x="-495"  y="805"   id="titanium-ore-37"  xlink:href="#titanium-ore"/>
	<use x="-405"  y="865"   id="titanium-ore-38"  xlink:href="#titanium-ore"/>
	<use x="-512"  y="867"   id="titanium-ore-39"  xlink:href="#titanium-ore"/>
	<use x="-455"  y="905"   id="titanium-ore-40"  xlink:href="#titanium-ore"/>
```

2016-12-13 02:03 UTC, salkinium commented on 2017/playground.svg
>  	<!-- identifiers ordered -y => +y -->
I'll leave crater 1 and 6 for you ;-P

2016-12-15 16:37 UTC, daniel-k commented
@JuliaGut thanks for helping out and adding your changes! I took the liberty to prepend `2017:` to your commits 😄 

@salkinium I think we're done now. Please check again if you like, otherwise we can merge.

2016-12-15 18:42 UTC, salkinium approved these changes

2016-12-15 18:42 UTC, salkinium commented
Yup, the changes look very good to me!

2016-12-15 18:44 UTC, salkinium commented
@daniel-k I think it's better if you assume ownership and maintenance of this repo, since I'm not that involved with Eurobot anymore. Is that ok with you?

2016-12-15 21:46 UTC, daniel-k commented
> @daniel-k I think it's better if you assume ownership and maintenance of this repo, since I'm not that involved with Eurobot (and RCA) anymore. Is that ok with you?

I would rather vote for @rleh but since everyone in `roboterclubaachen` seems to have write permissions to this repository I would argue we go with collective ownership 😝

2016-12-15 21:46 UTC, merged